"""Run every in-silico experiment and write results + figures.

    cd lithium && python -m sim.run_all --n 500

Writes docs/SIMULATION_RESULTS.md, docs/figures/*.png and sim/results.json.
"""

from __future__ import annotations

import argparse
import json
import multiprocessing as mp
import time
from pathlib import Path

import numpy as np

from lithos.models import get_engine, get_model

from . import trials
from .population import make_population

ROOT = Path(__file__).resolve().parents[1]
FIG = ROOT / "docs" / "figures"

# Palette (reference data-viz palette): emphasis = model-informed in blue,
# usual care in greys; aqua for the second model-informed variant.
BLUE, AQUA, ORANGE = "#2a78d6", "#1baf7a", "#eb6834"
GREY_DARK, GREY_LIGHT = "#6f6e69", "#b5b3aa"
INK, INK2, MUTED, GRID, SURFACE = "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#fcfcfb"
TARGET_WASH = "#e6f0fb"


def _one(args):
    idx, n_pts, seed, truth_name, engine_name, which = args
    truth, engine = get_model(truth_name), get_engine(engine_name)
    vp = make_population(n_pts, truth, seed=seed)[idx]
    rng = np.random.default_rng(seed * 100003 + idx)
    out = {"pid": idx, "age": vp.cov(0).age, "egfr": vp.cov(0).egfr, "miss": vp.miss_prob}
    try:
        if "titration" in which:
            out["uc_step"] = trials.usual_care(vp, truth, np.random.default_rng(rng.integers(1 << 31)), "stepwise")
            out["uc_prop"] = trials.usual_care(vp, truth, np.random.default_rng(rng.integers(1 << 31)),
                                               "proportional")
            out["mipd"] = trials.model_informed(vp, truth, engine, np.random.default_rng(rng.integers(1 << 31)))
        if "anytime" in which:
            out["anytime"] = trials.any_time(vp, truth, engine, np.random.default_rng(rng.integers(1 << 31)))
        if "thiazide" in which:
            out["thiazide"] = trials.thiazide(vp, truth, engine, np.random.default_rng(rng.integers(1 << 31)))
        if "early" in which:
            out["early"] = trials.early_sampling(vp, truth, engine, np.random.default_rng(rng.integers(1 << 31)))
    except Exception as exc:  # keep the run going; report failures
        out["error"] = repr(exc)
    return out


def _pct(x):
    return f"{100 * np.mean(x):.0f}%"


def _med_iqr(x):
    x = np.asarray([v for v in x if v is not None], dtype=float)
    if x.size == 0:
        return "n/a"
    q1, m, q3 = np.percentile(x, [25, 50, 75])
    return f"{m:.0f} ({q1:.0f}-{q3:.0f})"


def summarise(rows: list[dict], meta: dict) -> str:
    L = ["# In-silico trial results", "",
         f"Generated by `python -m sim.run_all` - {meta['n']} virtual patients, seed {meta['seed']}, "
         f"truth model `{meta['truth']}`, engine prior `{meta['engine']}`, runtime {meta['runtime_min']:.1f} min.",
         "", "These are simulations: they show whether the mechanisms work under stated assumptions, "
         "not clinical effectiveness. See docs/SIMULATION.md for methods and caveats.", ""]
    errors = [r for r in rows if "error" in r]
    if errors:
        L += [f"Runs with errors: {len(errors)} (excluded).", ""]
    rows = [r for r in rows if "error" not in r]

    if rows and "mipd" in rows[0]:
        L += ["## 1. Titration to a 12-h level of 0.6-0.8 mmol/L", "",
              "| Outcome | Usual care (stepwise) | Usual care (proportional) | Model-informed |",
              "|---|---|---|---|"]
        arms = [("uc_step", "stepwise"), ("uc_prop", "proportional"), ("mipd", "model")]

        def row(label, fn):
            L.append(f"| {label} | " + " | ".join(fn([r[a] for r in rows]) for a, _ in arms) + " |")

        row("Blood tests during titration, median (IQR)", lambda xs: _med_iqr([x["tests"] for x in xs]))
        row("Confirmed stable within 8 weeks", lambda xs: _pct([x["confirmed_day"] is not None for x in xs]))
        row("Days to confirmed stable, median (IQR)", lambda xs: _med_iqr([x["confirmed_day"] for x in xs]))
        row("Final dose truly in 0.6-0.8", lambda xs: _pct([x["final_in_range"] for x in xs]))
        row("Final dose truly in 0.5-0.9", lambda xs: _pct([x["final_in_wide_range"] for x in xs]))
        row("On a truly therapeutic dose from day, median (IQR)",
            lambda xs: _med_iqr([x["therapeutic_day"] for x in xs]))
        row("Ever on a dose with true 12-h level > 1.0", lambda xs: _pct([x["days_on_dose_over_1"] > 0 for x in xs]))
        row("Dose changes, median (IQR)", lambda xs: _med_iqr([x["n_dose_changes"] for x in xs]))
        L.append("")

    at = [r["anytime"] for r in rows if "anytime" in r]
    if at:
        L += ["## 2. A level drawn at a convenient time: what would a correctly timed level have shown?", "",
              "| Hours after evening dose | n | Naive: median abs error | Engine: median abs error | "
              "Engine + 1 earlier level | Naive: wrong category | Engine: wrong category | 90% CrI coverage |",
              "|---|---|---|---|---|---|---|---|"]

        def cat(v):
            return 0 if v < 0.6 else (2 if v > 0.8 else 1)

        bins = [(2, 6), (6, 10), (10, 14), (14, 18), (18, 22), (2, 22)]
        for lo, hi in bins:
            sub = [a for a in at if lo <= a["hours"] < hi or (hi == 22 and a["hours"] == 22)]
            if not sub:
                continue
            tr = np.array([a["truth12"] for a in sub])
            nv = np.array([a["naive"] for a in sub])
            en = np.array([a["engine_med"] for a in sub])
            eh = np.array([a["hist_med"] for a in sub])
            cov = np.mean([a["engine_lo"] <= a["truth12"] <= a["engine_hi"] for a in sub])
            wn = np.mean([cat(a["naive"]) != cat(a["truth12"]) for a in sub])
            we = np.mean([cat(a["engine_med"]) != cat(a["truth12"]) for a in sub])
            label = "All" if (lo, hi) == (2, 22) else f"{lo}-{hi} h"
            L.append(f"| {label} | {len(sub)} | {np.median(np.abs(nv - tr)):.3f} | {np.median(np.abs(en - tr)):.3f} | "
                     f"{np.median(np.abs(eh - tr)):.3f} | {100 * wn:.0f}% | {100 * we:.0f}% | {100 * cov:.0f}% |")
        L += ["", "Wrong category = below / within / above 0.6-0.8 mmol/L disagrees with the correctly timed truth.", ""]

    th = [r["thiazide"] for r in rows if "thiazide" in r]
    if th:
        na = np.array([t["no_action"] for t in th])
        ea = np.array([t["engine_adjusted"] for t in th])
        base = np.array([t["base"] for t in th])
        cover = np.mean([t["pred_lo"] <= t["no_action"] <= t["pred_hi"] for t in th])
        L += ["## 3. Thiazide started in a stable patient", "",
              "| True 12-h level after starting | No lithium change | Engine-adjusted dose |", "|---|---|---|",
              f"| > 1.0 mmol/L | {_pct(na > 1.0)} | {_pct(ea > 1.0)} |",
              f"| > 1.2 mmol/L | {_pct(na > 1.2)} | {_pct(ea > 1.2)} |",
              f"| In 0.6-0.8 | {_pct((na >= 0.6) & (na <= 0.8))} | {_pct((ea >= 0.6) & (ea <= 0.8))} |",
              f"| In 0.5-0.9 | {_pct((na >= 0.5) & (na <= 0.9))} | {_pct((ea >= 0.5) & (ea <= 0.9))} |",
              f"| < 0.5 mmol/L | {_pct(na < 0.5)} | {_pct(ea < 0.5)} |",
              f"| Median (IQR) | {np.median(na):.2f} ({np.percentile(na, 25):.2f}-{np.percentile(na, 75):.2f}) | "
              f"{np.median(ea):.2f} ({np.percentile(ea, 25):.2f}-{np.percentile(ea, 75):.2f}) |", "",
              f"Baseline (before the thiazide) median {np.median(base):.2f}. The engine's 90% forecast interval for the "
              f"no-change level contained the truth in {100 * cover:.0f}% of patients.", ""]

    ea_rows = [e for r in rows if "early" in r for e in r["early"]]
    if ea_rows:
        L += ["## 4. How soon after a dose change is a level informative?", "",
              "Median absolute error in the estimated new steady-state 12-h level (mmol/L), by day of sampling after the change.",
              "", "| Day after change | Naive (level as-is) | Engine, no earlier level | Engine + earlier level on old dose |",
              "|---|---|---|---|"]
        for d in sorted({e["day"] for e in ea_rows}):
            sub = [e for e in ea_rows if e["day"] == d]
            tr = np.array([e["truth"] for e in sub])
            L.append(f"| {d} | {np.median(np.abs(np.array([e['naive'] for e in sub]) - tr)):.3f} | "
                     f"{np.median(np.abs(np.array([e['no_history'] for e in sub]) - tr)):.3f} | "
                     f"{np.median(np.abs(np.array([e['with_history'] for e in sub]) - tr)):.3f} |")
        L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def _style(ax):
    ax.set_facecolor(SURFACE)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color("#c3c2b7")
        ax.spines[s].set_linewidth(0.8)
    ax.tick_params(colors=MUTED, labelcolor=INK2, labelsize=9, length=0)
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)


def figures(rows: list[dict]):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 10, "text.color": INK,
                         "axes.labelcolor": INK2, "figure.facecolor": SURFACE})
    FIG.mkdir(parents=True, exist_ok=True)
    rows = [r for r in rows if "error" not in r]

    if rows and "mipd" in rows[0]:
        arms = [("uc_step", "Usual care\n(stepwise)", GREY_LIGHT), ("uc_prop", "Usual care\n(proportional)", GREY_DARK),
                ("mipd", "Model-informed", BLUE)]
        metrics = [
            ("Blood tests during titration (mean)", lambda xs: np.mean([x["tests"] for x in xs]), "{:.1f}"),
            ("Final dose truly in 0.6-0.8 (%)", lambda xs: 100 * np.mean([x["final_in_range"] for x in xs]), "{:.0f}%"),
            ("Ever on a dose with true level > 1.0 (%)",
             lambda xs: 100 * np.mean([x["days_on_dose_over_1"] > 0 for x in xs]), "{:.0f}%"),
        ]
        fig, axes = plt.subplots(1, 3, figsize=(11, 3.6))
        for ax, (title, fn, fmt) in zip(axes, metrics):
            _style(ax)
            vals = [fn([r[a] for r in rows]) for a, _, _ in arms]
            x = np.arange(len(arms))
            ax.bar(x, vals, width=0.5, color=[c for _, _, c in arms], zorder=2)
            for xi, v in zip(x, vals):
                ax.text(xi, v, " " + fmt.format(v), ha="center", va="bottom", fontsize=9, color=INK)
            ax.set_xticks(x, [lab for _, lab, _ in arms], fontsize=8.5)
            ax.set_title(title, fontsize=10, color=INK, loc="left")
            ax.set_ylim(0, max(vals) * 1.25 + 1e-9)
        fig.suptitle("Titration to 0.6-0.8 mmol/L: usual care vs model-informed dosing (simulated)",
                     x=0.01, ha="left", fontsize=11.5, color=INK)
        fig.tight_layout()
        fig.savefig(FIG / "titration.png", dpi=160)
        plt.close(fig)

    at = [r["anytime"] for r in rows if "anytime" in r]
    if at:
        fig, ax = plt.subplots(figsize=(7.5, 4.0))
        _style(ax)
        edges = np.arange(2, 23, 2)
        mids = (edges[1:] + edges[:-1]) / 2
        series = [("naive", "Level read at face value", GREY_DARK), ("engine_med", "Engine, this level only", BLUE),
                  ("hist_med", "Engine + one earlier level", AQUA)]
        for key, label, color in series:
            ys = []
            for lo, hi in zip(edges[:-1], edges[1:]):
                sub = [a for a in at if lo <= a["hours"] < hi]
                ys.append(np.median([abs(a[key] - a["truth12"]) for a in sub]) if sub else np.nan)
            ax.plot(mids, ys, color=color, linewidth=2, marker="o", markersize=5, label=label,
                    markeredgecolor=SURFACE, markeredgewidth=1.5, zorder=3)
            ax.annotate(label, (mids[-1], ys[-1]), xytext=(6, 0), textcoords="offset points", va="center",
                        fontsize=8.5, color=INK2)
        ax.axvspan(11, 13, color=TARGET_WASH, zorder=0)
        ax.text(12, ax.get_ylim()[1] * 0.97, "12 h", ha="center", va="top", fontsize=8.5, color=INK2)
        ax.set_xlabel("Hours between evening dose and blood draw")
        ax.set_ylabel("Median absolute error (mmol/L)")
        ax.set_xlim(2, 26.5)
        ax.legend(frameon=False, fontsize=8.5, loc="upper center", ncol=3, bbox_to_anchor=(0.45, -0.18))
        ax.set_title("Reading a mistimed level vs standardising it with the model (simulated)",
                     loc="left", fontsize=11, color=INK)
        fig.tight_layout()
        fig.savefig(FIG / "anytime.png", dpi=160)
        plt.close(fig)

    th = [r["thiazide"] for r in rows if "thiazide" in r]
    if th:
        fig, ax = plt.subplots(figsize=(7.5, 3.8))
        _style(ax)
        bins = np.arange(0.2, 2.01, 0.05)
        ax.axvspan(0.6, 0.8, color=TARGET_WASH, zorder=0)
        ax.hist([t["no_action"] for t in th], bins=bins, color=GREY_DARK, alpha=0.9, label="No lithium change",
                histtype="stepfilled", zorder=2)
        ax.hist([t["engine_adjusted"] for t in th], bins=bins, color=BLUE, alpha=0.75, label="Engine-adjusted dose",
                histtype="stepfilled", zorder=3)
        ax.axvline(1.0, color=MUTED, linewidth=1)
        ax.text(1.01, ax.get_ylim()[1] * 0.95, "1.0", fontsize=8.5, color=INK2, va="top")
        ax.set_xlabel("True 12-h level after starting the thiazide (mmol/L)")
        ax.set_ylabel("Patients")
        ax.legend(frameon=False, fontsize=9)
        ax.set_title("Thiazide started in stable patients: forecast-and-adjust vs no change (simulated)",
                     loc="left", fontsize=11, color=INK)
        fig.tight_layout()
        fig.savefig(FIG / "thiazide.png", dpi=160)
        plt.close(fig)

    ea_rows = [e for r in rows if "early" in r for e in r["early"]]
    if ea_rows:
        fig, ax = plt.subplots(figsize=(7.5, 3.8))
        _style(ax)
        days = sorted({e["day"] for e in ea_rows})
        for key, label, color in [("naive", "Level read at face value", GREY_DARK),
                                  ("no_history", "Engine, no earlier level", BLUE),
                                  ("with_history", "Engine + earlier level on old dose", AQUA)]:
            ys = [np.median([abs(e[key] - e["truth"]) for e in ea_rows if e["day"] == d]) for d in days]
            ax.plot(days, ys, color=color, linewidth=2, marker="o", markersize=5, label=label,
                    markeredgecolor=SURFACE, markeredgewidth=1.5)
        ax.set_xlabel("Day of sampling after a dose change")
        ax.set_ylabel("Median absolute error (mmol/L)")
        ax.set_xticks(days)
        ax.legend(frameon=False, fontsize=9)
        ax.set_title("How soon after a dose change is a level useful? (simulated)", loc="left", fontsize=11, color=INK)
        fig.tight_layout()
        fig.savefig(FIG / "early.png", dpi=160)
        plt.close(fig)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=500)
    ap.add_argument("--seed", type=int, default=2026)
    ap.add_argument("--truth", default="truth-perturbed")
    ap.add_argument("--engine", default="ensemble", help='"ensemble" or a single model name')
    ap.add_argument("--which", default="titration,anytime,thiazide,early")
    ap.add_argument("--procs", type=int, default=mp.cpu_count())
    ap.add_argument("--merge", action="store_true", help="update only the selected experiments in sim/results.json")
    a = ap.parse_args()
    engine = a.engine
    which = set(a.which.split(","))
    t0 = time.time()
    jobs = [(i, a.n, a.seed, a.truth, engine, which) for i in range(a.n)]
    with mp.Pool(a.procs) as pool:
        rows = []
        for k, r in enumerate(pool.imap_unordered(_one, jobs, chunksize=4)):
            rows.append(r)
            if (k + 1) % 50 == 0:
                print(f"  {k + 1}/{a.n} patients ({(time.time() - t0) / 60:.1f} min)", flush=True)
    rows.sort(key=lambda r: r["pid"])
    meta = {"n": a.n, "seed": a.seed, "truth": a.truth, "engine": engine, "runtime_min": (time.time() - t0) / 60}
    if a.merge:
        old = json.loads((ROOT / "sim" / "results.json").read_text())
        by_pid = {r["pid"]: r for r in old["rows"]}
        for r in rows:
            by_pid.setdefault(r["pid"], {}).update({k: v for k, v in r.items()})
        rows = [by_pid[k] for k in sorted(by_pid)]
        meta["runtime_min"] += old["meta"].get("runtime_min", 0.0)
    (ROOT / "sim" / "results.json").write_text(json.dumps({"meta": meta, "rows": rows}, default=float))
    md = summarise(rows, meta)
    (ROOT / "docs" / "SIMULATION_RESULTS.md").write_text(md + "\n")
    figures(rows)
    print(md)


if __name__ == "__main__":
    main()
